name: 'Saplings - Domain'
description: 'Base Domain Access configuration for modern Drupal.'
type: 'Site'
install:
  # Core.
  - menu_ui
  - node
  - path
  - path_alias
  - taxonomy
  # Contrib.
  - domain
  - domain_access
  - domain_access_logo
  - domain_alias
  - domain_config
  - domain_config_ui
  - domain_content
  - domain_entity
  - domain_login_restrict
  - domain_menus
  - domain_path
config:
  import:
    # Contrib.
    domain: '*'
    domain_access: '*'
    domain_alias: '*'
    domain_entity: '*'
    domain_path: '*'
    domain_config_ui: '*'
