domain_menus_menu_names: main
domain_menus_filter_node_autocomplete: 1
domain_menus_hide_from_menu_list: 0
domain_menus_hide_admin_toolbar_links: 0
domain_menus_content_types_available_menus:
  article: '0'
  page: '0'
  landing_page: '0'
  person: '0'
  program: '0'
domain_menus_default_parent_menu_name: ''
